### ISSUE TITLE
pip install results in FileNotFoundError

### ISSUE THREAD

**Issue by cybfox77** [GearPlug/microsoftgraph-python#1]
```
$ pip install microsoftgraph-python
Collecting microsoftgraph-python
  Using cached microsoftgraph-python-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0iq72_j4/microsoftgraph-python/setup.py", line 12, in <module>
        long_description=read('README.md'),
      File "/tmp/pip-build-0iq72_j4/microsoftgraph-python/setup.py", line 6, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-0iq72_j4/microsoftgraph-python/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0iq72_j4/microsoftgraph-python/
```

**Comment by ingmferrer** [comment]
I'm looking into this, in the meantime you can install this library with `pip install git+git://github.com/GearPlug/microsoftgraph-python.git`

**Comment by ingmferrer** [comment]
This has been fixed in commit https://github.com/GearPlug/microsoftgraph-python/commit/3305858a1d8ba1e8534a66e9198fc87f806ee307

Thanks for your report.
