### ISSUE TITLE
KeyError in Client

### ISSUE THREAD

**Issue by ggravlingen** [GearPlug/microsoftgraph-python#32]
Hi,

I'm getting this error after updating to 1.1.1. Not sure if this is a local issue or a bug? Noted some changes where made in nearby code in this PR: https://github.com/GearPlug/microsoftgraph-python/pull/29

```
Error in Microsoft login hook error Traceback (most recent call last):
  File "/workspaces/.../.../integrations/azure/aad/auth_hook.py", line 43, in handle_login
    user = client.users.get_me()
  File "/usr/src/.venv/lib/python3.8/site-packages/microsoftgraph/decorators.py", line 11, in helper
    return func(*args, **kwargs)
  File "/usr/src/.venv/lib/python3.8/site-packages/microsoftgraph/users.py", line 32, in get_me
    return self._client._get(self._client.base_url + "me", params=params)
  File "/usr/src/.venv/lib/python3.8/site-packages/microsoftgraph/client.py", line 227, in _get
    return self._paginate_response(response)
  File "/usr/src/.venv/lib/python3.8/site-packages/microsoftgraph/client.py", line 215, in _paginate_response
    data = list(response.data["value"])
KeyError: 'value'
```

**Comment by Free-devloper** [comment]
Me too Anyone resolved it yet?

**Comment by ingmferrer** [comment]
Release 1.1.2 should resolve this, please upgrade and let me know if everything works as expected.

**Comment by ggravlingen** [comment]
Unfortunately not, I'm getting the same error. The error is on line 215:
https://github.com/GearPlug/microsoftgraph-python/blob/0e3a6ccd51948a809be04edc47c87328881e9446/microsoftgraph/client.py#L215

**Comment by ggravlingen** [comment]
There are no errors now. Thank you!
